export { default as UserRegister } from "./userRegister/UserRegister";
export { default as Login } from "./login/Login";
export { default as RecoverPassword } from "./recoverPassword/RecoverPassword";
export { default as UserDashboard } from "./userDashboard/UserDashboard";
export { default as ChangePassword } from "./changePassword/ChangePassword";
export { default as ActivateAccount } from "./activeAccount/ActiveAccount";
export { default as Referrals } from "./referrals/Referrals";
export { default as UserProfile } from "./userProfile/UserProfile";
export { default as Teams } from "./referrals/Teams";