import {
  faHome,
  faSchool,
  faChevronRight,
  faChartLine,
  faMagnifyingGlassDollar,
  faMoneyBillTrendUp,
  faMoneyBill,
  faBullhorn,
  faPeopleGroup,
  faWallet,
  faFlag,
  faTicket,
  faHandHoldingDollar,
  faPiggyBank,
  faBuildingColumns,
  faCopy,
  faBox,
  faMoneyBillTransfer,
  faCoins,
  faClock,
  faCheck,
  faUsersLine,
} from "@fortawesome/free-solid-svg-icons";

import { MenuItem } from "../../../types";

export const menuItems: MenuItem[] = [
  {
    leftIcon: faHome,
    rightIcon: null,
    label: "Home",
    to: "/dashboard",
    enabled: true,
  },
  {
    leftIcon: faUsersLine,
    rightIcon: null,
    label: "Referrals",
    to: "/dashboard/referrals",
    enabled: true,
  },
  {
    leftIcon: faSchool,
    rightIcon: null,
    label: "Evox Academy",
    to: "#",
    enabled: false,
  },
  {
    leftIcon: faChartLine,
    rightIcon: faChevronRight,
    label: "Auto Trading",
    to: "#",
    enabled: false,
    subItems: [
      {
        leftIcon: faChartLine,
        rightIcon: null,
        label: "MAM Accounts",
        to: "#",
        enabled: false,
      },
      {
        leftIcon: faHandHoldingDollar,
        rightIcon: null,
        label: "Commissions",
        to: "#",
        enabled: false,
      },
    ],
  },
  {
    leftIcon: faMagnifyingGlassDollar,
    rightIcon: faChevronRight,
    label: "Bridge Funds",
    to: "#",
    enabled: false,
    subItems: [
      {
        leftIcon: faBuildingColumns,
        rightIcon: null,
        label: "Type Of Accounts",
        to: "#",
        enabled: false,
      },
      {
        leftIcon: faPiggyBank,
        rightIcon: null,
        label: "My Accounts",
        to: "#",
        enabled: false,
      },
    ],
  },
  {
    leftIcon: faMoneyBillTrendUp,
    rightIcon: null,
    label: "Bridge Markets",
    to: "#",
    enabled: false,
  },
  {
    leftIcon: faMoneyBill,
    rightIcon: faChevronRight,
    label: "Evox Synthetics",
    to: "#",
    enabled: false,
    subItems: [
      {
        leftIcon: faSchool,
        rightIcon: null,
        label: "Academic",
        to: "#",
        enabled: false,
      },
      {
        leftIcon: faCopy,
        rightIcon: null,
        label: "Syntetics Copy",
        to: "#",
        enabled: false,
      },
      {
        leftIcon: faHandHoldingDollar,
        rightIcon: null,
        label: "Commissions",
        to: "#",
        enabled: false,
      },
    ],
  },
  {
    leftIcon: faBullhorn,
    rightIcon: faChevronRight,
    label: "Evox Marketing",
    to: "#",
    enabled: false,
    subItems: [
      {
        leftIcon: faBox,
        rightIcon: null,
        label: "Packages",
        to: "#",
        enabled: false,
      },
      {
        leftIcon: faHandHoldingDollar,
        rightIcon: null,
        label: "Commissions",
        to: "#",
        enabled: false,
      },
    ],
  },
  {
    leftIcon: faPeopleGroup,
    rightIcon: null,
    label: "Comunity",
    to: "#",
    enabled: false,
  },
  {
    leftIcon: faWallet,
    rightIcon: faChevronRight,
    label: "Evox Wallet",
    to: "#",
    enabled: false,
    subItems: [
      {
        leftIcon: faCoins,
        rightIcon: null,
        label: "My Earnings",
        to: "#",
        enabled: false,
      },
      {
        leftIcon: faMoneyBillTransfer,
        rightIcon: null,
        label: "My withdrawals",
        to: "#",
        enabled: false,
      },
    ],
  },
  {
    leftIcon: faFlag,
    rightIcon: null,
    label: "Reports",
    to: "#",
    enabled: false,
  },
  {
    leftIcon: faTicket,
    rightIcon: faChevronRight,
    label: "Support Ticket",
    to: "#",
    enabled: false,
    subItems: [
      {
        leftIcon: faCheck,
        rightIcon: null,
        label: "Ticket Request",
        to: "#",
        enabled: false,
      },
      {
        leftIcon: faClock,
        rightIcon: null,
        label: "History",
        to: "#",
        enabled: false,
      },
    ],
  },
];
